-- One-line patch notes (`updates`) scraped from live choosology.com Recent Updates.
-- DDL: id, `text` varchar(225), whenposted. Truncate text to 225 to match schema.
-- Safe to re-run on an empty table; skip if you already have local rows you care about.

DELETE FROM updates;
ALTER TABLE updates AUTO_INCREMENT = 1;

INSERT INTO updates (`text`, whenposted) VALUES ('prevented hotlinking pictures from this site, also prevented anyone trying to find more pictures by digging through directories', '2009-07-05 16:13:00');
INSERT INTO updates (`text`, whenposted) VALUES ('"Manage Pictures" section now has expandable categories.', '2009-07-05 16:13:00');
INSERT INTO updates (`text`, whenposted) VALUES ('Made this cute little auto-magical update listing.', '2009-07-05 16:14:00');
INSERT INTO updates (`text`, whenposted) VALUES ('fixed screen display error with HTML entities', '2009-07-05 21:21:00');
INSERT INTO updates (`text`, whenposted) VALUES ('warn if picture chosen but "[[pic]]" not written', '2009-07-06 00:13:00');
INSERT INTO updates (`text`, whenposted) VALUES ('picture alignment and borders are now explicit options. This means the old way ("[[pic|center|2px solid black]]") does not work anymore', '2009-07-06 00:14:00');
INSERT INTO updates (`text`, whenposted) VALUES ('Fixed issue where adventures would try to show an icon even if none was set.', '2009-07-06 00:15:00');
INSERT INTO updates (`text`, whenposted) VALUES ('Picture sizes are now shown on the Manage Pictures page.', '2009-07-06 19:05:00');
INSERT INTO updates (`text`, whenposted) VALUES ('you can now change a picture''s category from the Manage Pictures pages.', '2009-07-06 20:42:00');
INSERT INTO updates (`text`, whenposted) VALUES ('You can now reset your password if you forget it.', '2009-07-06 22:14:00');
INSERT INTO updates (`text`, whenposted) VALUES ('fixed a bug with displaying some icons on the Adventure editing page.', '2009-07-06 22:53:00');
INSERT INTO updates (`text`, whenposted) VALUES ('Can now put hyperlinks in screens.', '2009-07-07 00:20:00');
INSERT INTO updates (`text`, whenposted) VALUES ('fixed a bug where an error message was shown when editing adventures.', '2009-07-07 13:48:00');
INSERT INTO updates (`text`, whenposted) VALUES ('Forum link added.', '2009-07-07 23:33:00');
INSERT INTO updates (`text`, whenposted) VALUES ('"forum.cyocyoa.com" now redirects to the forum.', '2009-07-08 15:59:00');
INSERT INTO updates (`text`, whenposted) VALUES ('Added a "Recent Adventures" listing on the front page', '2009-07-09 01:13:00');
INSERT INTO updates (`text`, whenposted) VALUES ('Parent listing on screen editing page shows screen name instead of title.', '2009-07-09 10:41:00');
INSERT INTO updates (`text`, whenposted) VALUES ('Fixed style problems on Recent Adventures listing.', '2009-07-09 16:37:00');
INSERT INTO updates (`text`, whenposted) VALUES ('Implemented 5-star rating system.', '2009-07-10 00:41:00');
INSERT INTO updates (`text`, whenposted) VALUES ('Can''t rate your own adventures anymore.. also, some CSS fixes', '2009-07-10 01:15:00');
INSERT INTO updates (`text`, whenposted) VALUES ('fixed a couple rating-related problems.', '2009-07-10 11:22:00');
INSERT INTO updates (`text`, whenposted) VALUES ('Prevented trying to preview a screen in progress which hadn''t been created yet.', '2009-07-10 15:50:00');
INSERT INTO updates (`text`, whenposted) VALUES ('Made several visual and functional updates to the Browse page.', '2009-07-14 00:36:00');
INSERT INTO updates (`text`, whenposted) VALUES ('fixed layout issues for IE6. In general, I don''t consider IE6 to be something i really support, but in this case it was ridiculous not to.', '2009-07-14 16:30:00');
INSERT INTO updates (`text`, whenposted) VALUES ('Added an option for persistent logins.', '2009-07-15 00:59:00');
INSERT INTO updates (`text`, whenposted) VALUES ('more IE6-centric CSS fixes.', '2009-07-15 10:31:00');
INSERT INTO updates (`text`, whenposted) VALUES ('Updated "About" section.', '2009-07-15 11:35:00');
INSERT INTO updates (`text`, whenposted) VALUES ('Update to Privacy Policy to reflect multiple cookies usage. Update to Terms relaxing requirements for Public adventures.', '2009-07-15 11:47:00');
INSERT INTO updates (`text`, whenposted) VALUES ('allowed Facebook to access images so you can share adventures there. It''s still a little hit-or-miss though.', '2009-07-15 21:05:00');
INSERT INTO updates (`text`, whenposted) VALUES ('Allowed editing adventure details on Public adventures. Still can''t change its screens though.', '2009-07-15 21:14:00');
INSERT INTO updates (`text`, whenposted) VALUES ('Moved Availability options to drop-down, added "Restricted" and implemented security to enforce it.', '2009-07-16 00:45:00');
INSERT INTO updates (`text`, whenposted) VALUES ('Added an option in the Accounts subsection to allow yourself to see Restricted adventures.', '2009-07-16 00:45:00');
INSERT INTO updates (`text`, whenposted) VALUES ('Fixed bug when creating new adventure.', '2009-07-16 20:37:00');
INSERT INTO updates (`text`, whenposted) VALUES ('Added "Restricted Only" option to Browse page for people who have chosen to see such content.', '2009-07-16 20:38:00');
INSERT INTO updates (`text`, whenposted) VALUES ('added some helpful text.', '2009-07-16 21:11:00');
INSERT INTO updates (`text`, whenposted) VALUES ('Fixed a bug where you''d be warned about not having written "[[pic]]" even if you had.', '2009-07-17 12:01:00');
INSERT INTO updates (`text`, whenposted) VALUES ('Added "view all news" option to front page.', '2009-07-20 21:36:00');
INSERT INTO updates (`text`, whenposted) VALUES ('Cannot register with a name solely comprised of numbers.', '2009-07-24 00:57:00');
INSERT INTO updates (`text`, whenposted) VALUES ('Added proto-profiles.', '2009-07-24 00:58:00');
INSERT INTO updates (`text`, whenposted) VALUES ('Profile pages updated with fancy search box.', '2009-07-25 01:40:00');
INSERT INTO updates (`text`, whenposted) VALUES ('Updated Manage Pics page with option to change image names, and some styling changes.', '2009-07-26 15:36:00');
INSERT INTO updates (`text`, whenposted) VALUES ('You can now add a profile picture on your Account page.', '2009-07-26 23:23:00');
INSERT INTO updates (`text`, whenposted) VALUES ('Divided Adventure Editing page into Info and Style sections.', '2009-08-02 19:22:00');
INSERT INTO updates (`text`, whenposted) VALUES ('Added several helpful messages for creating new adventures.', '2009-08-02 19:22:00');
INSERT INTO updates (`text`, whenposted) VALUES ('Added new image-choosing module in all relevant areas.', '2009-08-02 19:23:00');
INSERT INTO updates (`text`, whenposted) VALUES ('Added the ability to upload .zip files of images.', '2011-02-08 22:15:00');
INSERT INTO updates (`text`, whenposted) VALUES ('Fixed an error in viewing adventures.', '2011-04-16 16:38:00');
INSERT INTO updates (`text`, whenposted) VALUES ('Up. Dated. EVERYTHING.', '2011-05-20 14:11:00');
INSERT INTO updates (`text`, whenposted) VALUES ('2.0.1 updated! See news item.', '2011-05-22 22:20:00');
INSERT INTO updates (`text`, whenposted) VALUES ('Fixed bug with screen editing.', '2011-05-23 19:01:00');
INSERT INTO updates (`text`, whenposted) VALUES ('Updated About page and Terms and Conditions.', '2011-05-23 19:02:00');
INSERT INTO updates (`text`, whenposted) VALUES ('Improved detection of background brightness so site buttons and text are visible.', '2011-05-23 19:14:00');
INSERT INTO updates (`text`, whenposted) VALUES ('Made some fixes and improvements to image-inserting, so that an image uploaded in another window will be available the next time you open an Edit Screen window.', '2011-05-24 23:31:00');
INSERT INTO updates (`text`, whenposted) VALUES ('Various updates to button styles and visual editor usability', '2011-05-25 23:53:00');
INSERT INTO updates (`text`, whenposted) VALUES ('Fixed some issues related to Adventure availability.', '2011-05-26 19:17:00');
INSERT INTO updates (`text`, whenposted) VALUES ('Cleaned up AJAX saving so it''s less choppy.', '2011-05-26 19:17:00');
INSERT INTO updates (`text`, whenposted) VALUES ('Added a search box on the Browse page.', '2011-05-27 21:28:00');
INSERT INTO updates (`text`, whenposted) VALUES ('Started adding some helpful popup tooltips.', '2011-05-28 17:41:00');
INSERT INTO updates (`text`, whenposted) VALUES ('Added some browser detection so it''s clearer what you need.', '2011-05-28 17:41:00');
INSERT INTO updates (`text`, whenposted) VALUES ('Made improvements to Screen Editor usability.', '2011-05-29 17:16:00');
INSERT INTO updates (`text`, whenposted) VALUES ('Added a "view full picture" option to Manage Pictures.', '2011-05-30 00:12:00');
INSERT INTO updates (`text`, whenposted) VALUES ('Made registration a little more helpful on success.', '2011-05-30 19:22:00');
INSERT INTO updates (`text`, whenposted) VALUES ('Fixed some screen editor errors.', '2011-05-31 19:51:00');
INSERT INTO updates (`text`, whenposted) VALUES ('Added semi-experimental video embedding!', '2011-05-31 23:32:00');
INSERT INTO updates (`text`, whenposted) VALUES ('Fixed some bugs on the Account page.', '2011-06-01 22:29:00');
INSERT INTO updates (`text`, whenposted) VALUES ('You can now log in with your email OR username.', '2011-06-06 18:43:00');
INSERT INTO updates (`text`, whenposted) VALUES ('Fixed some bugs on the Profile page.', '2011-06-09 20:30:00');
INSERT INTO updates (`text`, whenposted) VALUES ('Fixed issue with universal images being used as adventure images.', '2011-10-07 15:44:00');
INSERT INTO updates (`text`, whenposted) VALUES ('The visual editor now has an indicator for when there are non-visible screens.', '2011-11-06 18:15:00');
INSERT INTO updates (`text`, whenposted) VALUES ('Fixed an issue with saving adventure options with a long adventure title.', '2013-01-11 09:37:00');
INSERT INTO updates (`text`, whenposted) VALUES ('Made a couple of fixes to ratings and description box errors.', '2013-03-05 15:56:00');
INSERT INTO updates (`text`, whenposted) VALUES ('Made a few fixes to places that were showing HTML code instead of parsing it.', '2013-04-11 16:35:00');
INSERT INTO updates (`text`, whenposted) VALUES ('Allowed deletion of own comments, and fixed comment display on home page.', '2013-04-13 16:26:00');
INSERT INTO updates (`text`, whenposted) VALUES ('A couple styling fixes, especially with how adventures are shown in Recent Adventures.', '2013-04-24 23:24:00');
INSERT INTO updates (`text`, whenposted) VALUES ('Added some controls for publishing to help prevent accidental publishing.', '2013-04-27 00:06:00');
INSERT INTO updates (`text`, whenposted) VALUES ('Fixed minor issue with Beginning Screen choice with disproportionately major rewrite of the functionality.', '2013-04-27 00:07:00');
INSERT INTO updates (`text`, whenposted) VALUES ('Tweaked adventure saving so large adventures are less likely to break.', '2013-05-15 23:32:00');
INSERT INTO updates (`text`, whenposted) VALUES ('Added loading overlay to prevent some bugs on adventure editor.', '2013-05-16 16:28:00');
INSERT INTO updates (`text`, whenposted) VALUES ('Added node counter and fixed issue with lingering node highlights.', '2013-05-16 17:25:00');
INSERT INTO updates (`text`, whenposted) VALUES ('Added "Send Message" button to profiles, fixed a couple message bugs.', '2013-05-17 14:53:00');
INSERT INTO updates (`text`, whenposted) VALUES ('Added a little button linking to our Facebook page.', '2013-05-22 23:11:00');
INSERT INTO updates (`text`, whenposted) VALUES ('Noticed and sorta-fixed a bug which can make adventure editing impossible.', '2013-05-27 18:43:00');
INSERT INTO updates (`text`, whenposted) VALUES ('Comments on non-public adventures are no longer shown in Recent Comments.', '2013-05-29 18:13:00');
INSERT INTO updates (`text`, whenposted) VALUES ('Updated Screen Editor to show which screens are empty or not.', '2013-06-26 12:26:00');
INSERT INTO updates (`text`, whenposted) VALUES ('Added a Total Word Count in Screen Editor.', '2013-06-30 16:21:00');
INSERT INTO updates (`text`, whenposted) VALUES ('By popular demand, the Screen Editor has been made larger.', '2013-08-18 08:04:00');
INSERT INTO updates (`text`, whenposted) VALUES ('Registration and the Privacy Policy have been updated to cover users under 13.', '2015-02-10 11:36:00');
INSERT INTO updates (`text`, whenposted) VALUES ('The forum (and forum button) has been removed.', '2017-02-05 15:19:00');
